#
###################################
# Site wide configuration
####################################
#
title: Tom Caruso
email: carusot42@gmail.com
description:
url: http://tcaruso.com
keywords: ["Python", "PostgreSQL", "Docker"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          America/New_York
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Tom Caruso
  avatar: angry_tom.png
  job: "Python, Postgres & Docker"
  bio: "Software engineer with focus on geospatial"
  email: carusot42@gmail.com
  disqus-shortname:
  twitter: astronomiser #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-62251910-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: tomplex #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: thomascaruso42 #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: tomplex #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
